[build]

command = "npm run prod"
publish = "build_production"
environment = { PHP_VERSION = "7.4", NODE_VERSION = "12.16.1" }
[[redirects]]

from = “/”

to = “/deals-2/”

status = 302

force = true

conditions = {Country = “in”}
