[build]

command = "npm run prod"
publish = "build_production"
environment = { PHP_VERSION = "7.4", NODE_VERSION = "12.16.1" }
[[redirects]]
[[redirects]]

  from = "/"

  to = "/in"

  status = 302

  force = false

  conditions = {Country = ["in"]}
