[build]

command = "npm run prod"
publish = "build_production"
environment = { PHP_VERSION = "7.4", NODE_VERSION = "12.16.1" }

# A redirect rule with many of the supported properties

[[redirects]]

  from = "/index"

  to = "/in:splat"

  status = 301

  # By default, redirects won’t be applied if there’s a file with the same

  # path as the one defined in the `from` property. Setting `force` to `true`

  # will make the redirect rule take precedence over any existing files.

  force = true

  # Redirect based on conditions including browser language, geolocation,

  # identity role, and/or cookie presence.

  conditions = {Country = ["IN"]}
